# -*- coding: utf-8 -*-
"""Valentines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUYaJATdlFzneSsaIqzVHGtsQHz7raV1
"""

import streamlit as st
import random
import os

# Page config
st.set_page_config(
    page_title="For Caitlin 💌",
    page_icon="💖",
    layout="centered"
)

# Pink background
st.markdown(
    """
    <style>
    .stApp {
        background-color: pink;
    }
    .center {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# Title
st.markdown(
    "<h1 style='text-align: center; color: #cc0066;'>Hiiiii baby 💕<br>Will you be my Valentine?</h1>",
    unsafe_allow_html=True
)

st.write("")
st.write("")

# Session state
if "show_gifs" not in st.session_state:
    st.session_state.show_gifs = False

if "no_margin" not in st.session_state:
    st.session_state.no_margin = random.randint(0, 50)

# Center buttons horizontally
st.markdown("<div class='center'>", unsafe_allow_html=True)

# "Yes" button
yes_clicked = st.button("Yes 💖")
if yes_clicked:
    st.session_state.show_gifs = True

# Add horizontal spacing
st.markdown("&nbsp;&nbsp;&nbsp;&nbsp;", unsafe_allow_html=True)

# "No" button with top margin (moves)
no_clicked = st.button("No 🙄")
if no_clicked:
    st.session_state.no_margin = random.randint(0, 50)
    st.rerun()

st.markdown("</div>", unsafe_allow_html=True)

# Move "No" button visually by top margin
st.markdown(
    f"<div style='margin-top:{st.session_state.no_margin}px'></div>",
    unsafe_allow_html=True
)

# Show GIFs after YES
if st.session_state.show_gifs:
    st.balloons()
    st.success("I knew you'd say yes 😘💖 I love you so much ❤️")

    st.write("")

    colA, colB = st.columns(2)

    # Use the correct folder and filenames
    gif1_path = os.path.join("Gifs", "Us_1.gif")
    gif2_path = os.path.join("Gifs", "Us_2.gif")

    with colA:
        st.image(gif1_path, use_container_width=True)

    with colB:
        st.image(gif2_path, use_container_width=True)

    st.markdown(
        "<h3 style='text-align:center;color:#cc0066;'>Forever Us 💞</h3>",
        unsafe_allow_html=True
    )