# -*- coding: utf-8 -*-
"""Valentines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUYaJATdlFzneSsaIqzVHGtsQHz7raV1
"""

import tkinter as tk
from tkinter import messagebox
from PIL import Image, ImageTk, ImageSequence
import random


# Main window
root = tk.Tk()
root.title("For Caitlin 💌")
root.geometry("400x300")
root.configure(bg="pink")


# Main text
label = tk.Label(
    root,
    text="Hiiiii baby 💕\n\nWill you be my Valentine?",
    font=("Modern Love", 18, "bold"),
    bg="pink",
    fg="#cc0066",
    justify="center"
)
label.pack(pady=40)


# Play two GIFs
def play_gifs():

    gif_window = tk.Toplevel(root)
    gif_window.title("Us 💖")
    gif_window.configure(bg="pink")
    gif_window.geometry("650x350")

    frame = tk.Frame(gif_window, bg="pink")
    frame.pack(pady=20)


    lbl1 = tk.Label(frame, bg="pink")
    lbl2 = tk.Label(frame, bg="pink")

    lbl1.grid(row=0, column=0, padx=10)
    lbl2.grid(row=0, column=1, padx=10)


    gif1 = Image.open("Us_1.gif")
    gif2 = Image.open("Us_2.gif")


    frames1 = []
    frames2 = []


    for frame in ImageSequence.Iterator(gif1):
        frame = frame.resize((300, 300))
        frames1.append(ImageTk.PhotoImage(frame))

    for frame in ImageSequence.Iterator(gif2):
        frame = frame.resize((300, 300))
        frames2.append(ImageTk.PhotoImage(frame))


    def animate(i=0, j=0):

        lbl1.configure(image=frames1[i])
        lbl2.configure(image=frames2[j])

        gif_window.after(
            100,
            animate,
            (i + 1) % len(frames1),
            (j + 1) % len(frames2)
        )


    animate()


# Yes button
def yes_clicked():

    messagebox.showinfo(
        "Yay! 💖",
        "I knew you'd say yes 😘\n\nI love you so much ❤️"
    )

    play_gifs()


# Move No button
def move_no(event=None):

    x = random.randint(0, 300)
    y = random.randint(150, 260)

    no_button.place(x=x, y=y)


# Buttons
yes_button = tk.Button(
    root,
    text="Yes 💖",
    font=("Arial", 14),
    bg="#ff4d88",
    fg="white",
    width=10,
    command=yes_clicked
)

no_button = tk.Button(
    root,
    text="No 🙄",
    font=("Arial", 14),
    bg="#cccccc",
    fg="black",
    width=10
)


yes_button.pack(pady=10)
no_button.place(x=160, y=220)


# Escape on hover AND click
no_button.bind("<Enter>", move_no)
no_button.bind("<Button-1>", move_no)


# Run app
root.mainloop()