# -*- coding: utf-8 -*-
"""Valentines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUYaJATdlFzneSsaIqzVHGtsQHz7raV1
"""

import streamlit as st
import random


# Page config
st.set_page_config(
    page_title="For Caitlin 💌",
    page_icon="💖",
    layout="centered"
)

# Pink background
st.markdown(
    """
    <style>
    .stApp {
        background-color: pink;
    }
    </style>
    """,
    unsafe_allow_html=True
)


# Title
st.markdown(
    "<h1 style='text-align: center; color: #cc0066;'>Hiiiii baby 💕<br>Will you be my Valentine?</h1>",
    unsafe_allow_html=True
)

st.write("")
st.write("")


# Session state
if "show_gifs" not in st.session_state:
    st.session_state.show_gifs = False

if "no_pos" not in st.session_state:
    st.session_state.no_pos = random.randint(0, 100)


# Button layout
col1, col2, col3 = st.columns([1, 1, 1])


# YES button
with col1:
    if st.button("Yes 💖"):
        st.session_state.show_gifs = True


# NO button (moves)
with col3:

    space = st.empty()

    if space.button("No 🙄"):
        st.session_state.no_pos = random.randint(0, 100)
        st.rerun()


# Move button using spacing
st.markdown(
    f"<div style='height:{st.session_state.no_pos}px'></div>",
    unsafe_allow_html=True
)


# Show GIFs after YES
if st.session_state.show_gifs:

    st.balloons()

    st.success("I knew you'd say yes 😘💖 I love you so much ❤️")

    st.write("")

    colA, colB = st.columns(2)

    with colA:
        st.image("Us_1.gif", use_container_width=True)

    with colB:
        st.image("Us_2.gif", use_container_width=True)


    st.markdown(
        "<h3 style='text-align:center;color:#cc0066;'>Forever Us 💞</h3>",
        unsafe_allow_html=True
    )